package com.example.intuit.businessprofileservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.intuit.businessprofileservice.entity.Address;
import com.example.intuit.businessprofileservice.util.AddressConverter;
import com.example.intuit.businessprofileservice.util.TaxIdentifierConverter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.util.Map;

//@JsonPropertyOrder({ "customerID", "companyName", "legalName", "email", "website" })
@DynamoDBTable(tableName = "BusinessProfile")
public class BusinessProfile implements Serializable {

    private static final long serialVersionUID = 7156526077883281623L;
    private String customerID;

    private String companyName;

    private String legalName;

    private String email;

    private String website;

    private Address businessAddress;

    private Address legalAddress;


    private Map<String, String> taxIdentifiers;

    private long lastUpdateTimestamp;

    // Partition key
    @DynamoDBHashKey(attributeName = "CustomerID")
    @DynamoDBAutoGeneratedKey
    public String getCustomerID() {
        return customerID;
    }

    public void setCustomerID(String customerID) {
        this.customerID = customerID;
    }

    @DynamoDBAttribute(attributeName = "CompanyName")
    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @DynamoDBAttribute(attributeName = "LegalName")
    public String getLegalName() {
        return legalName;
    }

    public void setLegalName(String legalName) {
        this.legalName = legalName;
    }
    @DynamoDBAttribute(attributeName = "Email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName = "Website")
    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    @DynamoDBAttribute(attributeName = "BusinessAddress")
    @DynamoDBTypeConverted(converter = AddressConverter.class)
    public Address getBusinessAddress() {
        return businessAddress;
    }

    public void setBusinessAddress(Address businessAddress) {
        this.businessAddress = businessAddress;
    }

    @DynamoDBAttribute(attributeName = "LegalAddress")
    @DynamoDBTypeConverted(converter = AddressConverter.class)
    public Address getLegalAddress() {
        return legalAddress;
    }

    public void setLegalAddress(Address legalAddress) {
        this.legalAddress = legalAddress;
    }

    @DynamoDBAttribute(attributeName = "TaxIdentifiers")
    @DynamoDBTypeConverted(converter = TaxIdentifierConverter.class)
    public Map<String, String> getTaxIdentifiers() {
        return taxIdentifiers;
    }

    public void setTaxIdentifiers(Map<String, String> taxIdentifiers) {
        this.taxIdentifiers = taxIdentifiers;
    }

    @DynamoDBAttribute(attributeName = "LastUpdateTimestamp")
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    public long getLastUpdateTimestamp() {
        return lastUpdateTimestamp;
    }

    public void setLastUpdateTimestamp(long lastUpdateTimestamp) {
        this.lastUpdateTimestamp = lastUpdateTimestamp;
    }

}

