package com.example.intuit.businessprofileservice.model;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "Subscription")
//@JsonPropertyOrder({  "productID", "id" , "customerID"})
public class Subscription {

    @Id
    private SubscriptionId subscriptionId;

    private String productID;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return subscriptionId!=null ? subscriptionId.getId() : null;
    }

    public void setId(String id) {

        if (subscriptionId == null) {
            subscriptionId = new SubscriptionId();
        }
        subscriptionId.setId(id);

    }

    @DynamoDBRangeKey(attributeName = "CustomerID")
    public String getCustomerID() {
        return subscriptionId!=null ? subscriptionId.getCustomerID() : null;
    }

    public void setCustomerID(String id) {

        if (subscriptionId == null) {
            subscriptionId = new SubscriptionId();
        }
        subscriptionId.setCustomerID(id);

    }


    @DynamoDBAttribute(attributeName = "ProductID")
    public String getProductID() {
        return productID;
    }

    public void setProductID(String productID) {
        this.productID = productID;
    }
}
